version: '3'
services:
  db:
    build: .
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: shiori
